[project]
name = "websearcher"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "beepscore", email = "support@beepscore.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "selenium>=4.38.0",
]

[project.scripts]
websearcher = "websearcher:main"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
