#!/usr/bin/env bash

# activate virtual environment in directory venv, in case user didn't already do it
source venv/bin/activate
# In terminal show that venv is active by showing python path and version python 3.x
# NOTE: If virtual environment was not active before script started, after script finishes apparently venv is deactivated
which python
python --version

# Use shell script to explicitly list each test instead of python3 -m unittest discover.
# python3 -m unittest discover confused test_arg_reader.
# test_arg_reader thought discover was an argument for it.
python3 test_web_downloader_arg_reader.py
python3 test_web_searcher_arg_reader.py
python3 test_page_reader.py
python3 test_file_writer.py
python3 test_web_downloader.py
python3 test_web_searcher.py

