#!/usr/bin/env bash

# Use shell script to explicitly list each test instead of python3 -m unittest discover.
# python3 -m unittest discover confused test_arg_reader.
# test_arg_reader thought discover was an argument for it.
python3 test_arg_reader.py
python3 test_page_reader.py
python3 test_file_writer.py

